version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smissi_postgres
    environment:
      POSTGRES_USER: smissi
      POSTGRES_PASSWORD: smissi_dev
      POSTGRES_DB: smissi
    ports:
      - '5433:5432'
    volumes:
      - smissi_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U smissi -d smissi']
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: smissi_redis
    ports:
      - '6380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  smissi_pgdata:
